export enum ConversationStep {
  SELECT_SERVICE = 'SELECT_SERVICE',
  SELECT_PROFESSIONAL = 'SELECT_PROFESSIONAL',
  SELECT_DATE = 'SELECT_DATE',
  SELECT_TIME = 'SELECT_TIME',
  CONFIRMATION = 'CONFIRMATION',
}
